#!/usr/bin/env python3
"""
check_staleness.py
Checks each RSS feed in sources.yaml for recent activity.
Sources with no posts in STALE_DAYS days are flagged.
Opens a GitHub issue summarising all stale sources.

Runs in GitHub Actions; needs GITHUB_TOKEN env var.
"""

import json
import os
import sys
from datetime import datetime, timezone, timedelta
from pathlib import Path

try:
    import feedparser
    import requests
    import yaml
except ImportError:
    print("Missing deps. Run: pip install pyyaml feedparser requests")
    sys.exit(1)

STALE_DAYS = 90
REPO = os.environ.get("GITHUB_REPOSITORY", "amikumar91/ai-signal")
TOKEN = os.environ.get("GITHUB_TOKEN", "")


def load_sources(path: Path):
    with path.open() as f:
        return yaml.safe_load(f)["sources"]


def latest_post_date(rss_url: str) -> datetime | None:
    """Return the datetime of the most recent feed entry, or None on failure."""
    try:
        feed = feedparser.parse(rss_url)
        if not feed.entries:
            return None
        entry = feed.entries[0]
        for field in ("published_parsed", "updated_parsed"):
            t = getattr(entry, field, None)
            if t:
                return datetime(*t[:6], tzinfo=timezone.utc)
    except Exception:
        pass
    return None


def open_github_issue(title: str, body: str):
    if not TOKEN:
        print("No GITHUB_TOKEN — skipping issue creation")
        print(f"\nWould have opened issue: {title}\n{body}")
        return
    resp = requests.post(
        f"https://api.github.com/repos/{REPO}/issues",
        headers={"Authorization": f"token {TOKEN}", "Accept": "application/vnd.github+json"},
        json={"title": title, "body": body, "labels": ["staleness"]},
    )
    if resp.ok:
        print(f"Opened issue: {resp.json()['html_url']}")
    else:
        print(f"Failed to open issue: {resp.status_code} {resp.text}", file=sys.stderr)


def main():
    sources = load_sources(Path("sources.yaml"))
    now = datetime.now(timezone.utc)
    cutoff = now - timedelta(days=STALE_DAYS)

    stale = []
    error = []

    for s in sources:
        rss = s.get("rss")
        if not rss or s.get("activity") == "archived":
            continue

        print(f"Checking: {s['name']} ...", end=" ", flush=True)
        latest = latest_post_date(rss)

        if latest is None:
            error.append(s)
            print("⚠ could not fetch")
        elif latest < cutoff:
            days_ago = (now - latest).days
            s["_days_since"] = days_ago
            s["_latest"] = latest.strftime("%Y-%m-%d")
            stale.append(s)
            print(f"⚠ stale ({days_ago}d ago)")
        else:
            print(f"✓ ({latest.strftime('%Y-%m-%d')})")

    if not stale and not error:
        print("\nAll sources are fresh 🎉")
        return

    # Build issue body
    lines = [f"# Staleness report — {now.strftime('%Y-%m-%d')}\n"]
    lines.append(f"Sources with no posts in the last **{STALE_DAYS} days** need review.")
    lines.append("Please check each source and either:\n- Update `activity: slow` or `activity: archived` in `sources.yaml`\n- Or confirm it's still worth keeping.\n")

    if stale:
        lines.append("## Stale sources\n")
        lines.append("| Source | Last post | Days since | Action |")
        lines.append("|--------|-----------|------------|--------|")
        for s in sorted(stale, key=lambda x: x["_days_since"], reverse=True):
            url = s.get("url", "")
            lines.append(f"| [{s['name']}]({url}) | {s['_latest']} | {s['_days_since']}d | [ ] confirm/archive |")

    if error:
        lines.append("\n## Feed errors (could not fetch)\n")
        for s in error:
            lines.append(f"- [{s['name']}]({s.get('url','')}) — RSS: `{s.get('rss','')}`")

    lines.append(f"\n---\n*Generated by the weekly staleness check. Edit `sources.yaml` and close this issue when resolved.*")

    body = "\n".join(lines)
    title = f"Staleness check: {len(stale)} stale, {len(error)} feed errors ({now.strftime('%Y-%m-%d')})"
    open_github_issue(title, body)


if __name__ == "__main__":
    main()
